import React from 'react';
import { Link } from 'react-router-dom';

// generated by copilot
const Home = () => {
  return (
    <header className="App-header">
      <div className="welcome-container">
        <h1 className="main-title">
          Welcome to Github Copilot AI Productivity Capability uplift
        </h1>
        <h2 className="sub-title">
          Made by Github Copilot and the 2 best teams in GFS!
        </h2>
        {/* generated by copilot */}
        <div className="feature-grid">
          <Link to="/experiment1" className="feature-card-link">
            <div className="feature-card">
              <h3>🚀 Experiment 1</h3>
              <p>Group 1</p>
              <button className="explore-button">Explore Experiment 1</button>
            </div>
          </Link>
          <Link to="/experiment2" className="feature-card-link">
            <div className="feature-card">
              <h3>⚡ Experiment 2</h3>
              <p>Group 2</p>
              <button className="explore-button">Explore Experiment 2</button>
            </div>
          </Link>
          <Link to="/experiment3" className="feature-card-link">
            <div className="feature-card">
              <h3>🎯 Experiment 3</h3>
              <p>Group 3</p>
              <button className="explore-button">Explore Experiment 3</button>
            </div>
          </Link>
          <Link to="/add-experiment" className="feature-card-link">
            <div className="feature-card placeholder-card">
              <h3>➕ Add Your Experiment</h3>
              <p>Create your own experiment page</p>
              <button className="explore-button">Get Started</button>
            </div>
          </Link>
        </div>
      </div>
    </header>
  );
};

export default Home; // generated by copilot